DROP USER OMS CASCADE;
CREATE USER OMS IDENTIFIED BY Dmdd@2025;
ALTER USER OMS DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER OMS TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO OMS;
GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE TO
OMS;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO OMS;